spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workout_db
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: exercises_be

flyway:
  enabled: true
  url: jdbc:mysql://localhost:3306/workout_db
  user: root
  password: test1234

app:
  jwt:
    secret: my-secret-key
    expirationMs: 3600000
    refreshExpirationMs: 86400000